### ISSUE TITLE
Allow `Value` to be any type instead of the union `string | number | string[]`

### ISSUE THREAD

**Issue by emi2k01** [jaredLunde/form-atoms#11]
**Is your feature request related to a problem? Please describe.**
I have some fields whose value is an ID to an object but I store another value from the object to show the user. So I'd like to do something like:

```ts
user: fieldAtom(value: {
  id: null,
  name: "",
})
```

This way, I can update the values atomically.

**Describe the solution you'd like**
I would like to be able to add any value to a fieldAtom and be able to use them with components such as `Field`.

**Describe alternatives you've considered**
Use two fields.

**Additional context**
...

**Comment by jaredLunde** [comment]
It might be a mistake on my part that `<Field>` has this restriction. I think that should only apply to `<InputField>` where there are `onChange` and `onBlur` prop dependencies. It's definitely the intent that `<Field>` be a less restrictive component.

**Comment by emi2k01** [comment]
Awesome, thanks!
