### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by jaredLunde** [jaredLunde/form-atoms#20]
- [x] Use the [Jotai v2 API](https://jotai.org/docs/guides/migrating-to-v2-api)
  - Replace `scope` with `store` and context
  - `await get()`
  - `initialValues={[[countAtom, 1]]}` is replaced by `createStore()` and `store.set()`
  - Maybe do something with abort signals
- [x] Create a `useInputFieldAtom()` hook, remove `props` from `useFieldAtom()`
        https://github.com/jaredLunde/form-atoms/issues/18#issuecomment-1407439522
- [x] Maybe add `form-atoms/zod` validator       
        https://github.com/jaredLunde/form-atoms/issues/17#issuecomment-1407415550
   - For consideration: https://github.com/jaredLunde/form-atoms/pull/23
- [x] `FormValues` and `FormErrors` should infer fields from form instead of using fields as the generic 
          https://github.com/jaredLunde/form-atoms/issues/28
- [x] Fix incorrect `dirty` value when `initialValue` is used
- [x] Fix reset doesn't set value to the value in `useFieldInitialValue` 
         https://github.com/jaredLunde/form-atoms/pull/33
- [x] Fix https://github.com/jaredLunde/form-atoms/issues/26
- [x] Update CodeSandbox examples
- [x] Use `tsup` for build step
- [x] Use `vitest` for tests
- [x] Pin package versions in `devDependencies`
- [x] Fix GitHub build badge
- [x] Remove `.tsbuildinfo` and `types` directory
- [x] Add `prettier` to `eslint` config instead of running them separately

**Comment by MiroslavPetrik** [comment]
[Jotai will have new API from v2](https://jotai.org/docs/guides/migrating-to-v2-api) so could be updated as well.

**Comment by jaredLunde** [comment]
Ahhh yes thanks for the link. Definitely need to add that to the list.

**Comment by jaredLunde** [comment]
Created a `next` prerelease branch if you want to contribute to any of the above
https://github.com/jaredLunde/form-atoms/tree/next

**Comment by MiroslavPetrik** [comment]
jotai v2 just landed
https://github.com/pmndrs/jotai/releases/tag/v2.0.0

**Comment by jaredLunde** [comment]
Awesome! Will get started on the updates

**Comment by MiroslavPetrik** [comment]
This looks amazing. Let's release!
