### ISSUE TITLE
Submitting form after removing last item from array fields returns empty object

### ISSUE THREAD

**Issue by MiroslavPetrik** [jaredLunde/form-atoms#26]
Maybe just undefined behavior, but from consistency standpoint I think the following can be improved:

**To Reproduce**
1. [open array fields example](https://codesandbox.io/s/form-atoms-array-fields-example-5evmlz?file=/src/App.tsx)
2. delete the initial hobby by clicking the gray button
3. click submit blue button
4. `{}` appears in the alert window

**Expected behavior**
I would expect `{ hobbies: [] }` as the submit value

The empty object is also inconsistent with the inferred type:
```ts
FormAtomValues<{
    hobbies: {
        name: FieldAtom<string>;
    }[];
}>

// { hobbies: {name: string}[] }
```

**Additional context**
I consider the issue to be in the `valuesAtom` where the [walk over the fields happens.](https://github.com/jaredLunde/form-atoms/blob/main/src/index.tsx#L113)
Technically the `hobbies` array is not a field, so it's skipped.

I noticed that the library supports two kinds of arrays in the form fields object:
`FormAtomFields[] | FieldAtom<any>[]`

And that basically all the field atoms are eventually leafs of the tree of type `FormAtomFields`.
Eventually I will need to define some validation rules for the field array, e.g. to have minimum 1 hobbies or max 3.

It could be related to how the fix for above will be solved. Maybe there could be support for a type
`FieldAtom<FormAtomFields[] | FieldAtom<any>[]>` or something similar, but that would likely require more work, as the field atom could be in positions where it's not a leaf of the tree...

Maybe it even works now, I will try this case soon :)

**Comment by jared-paperspace** [comment]
Yeah this is definitely a bug. Will have to think on how best to fix it considering the visitor will only be called when atoms are found. 

Addressing the idea of an "array field" type - I do not agree with the approach of validating the array as a field in something like Zod as opposed using `.slice()` in your user code and validating each field individually:

- From a UX standpoint you are creating a subpar experience if you're letting users do things they aren't allowed to anyway (i.e. click a button to add a field you KNOW is going to fail validation). You shouldn't give your users footguns.
- From a practicality standpoint, there's no such thing as an "array input". Backends are the ones that interpret particular field names as arrays. 

So IMO your "validation" should really just be bounded configuration on an `<ArrayField minLen maxLen>` component or whatever.

**Comment by jaredLunde** [comment]
Yeah this is definitely a bug. Will have to think on how best to fix it considering the visitor will only be called when atoms are found.

Addressing the idea of an "array field" type - I do not agree with the approach of validating the array as a field in something like Zod as opposed using .slice() in your user code and validating each field individually:

- From a UX standpoint you are creating a subpar experience if you're letting users do things they aren't allowed to anyway (i.e. click a button to add a field you KNOW is going to fail validation). You shouldn't give your users footguns.
- From a practicality standpoint, there's no such thing as an "array input". Backends are the ones that interpret particular field names as arrays.

So IMO your "validation" should really just be bounded configuration on an <ArrayField minLen maxLen> component or whatever.

**Comment by MiroslavPetrik** [comment]
Works as expected with the @next version. Thank you!

**Comment by jaredLunde** [comment]
Will address this, thanks!
