### ISSUE TITLE
Set debug labels for the form atoms

### ISSUE THREAD

**Issue by MiroslavPetrik** [jaredLunde/form-atoms#40]
To simplify debugging, the [atom debug labels](https://jotai.org/docs/guides/debugging#debug-labels) can be used.

Currently all the atoms are unlabeled.
![image](https://user-images.githubusercontent.com/38855190/219967810-fc0b13dd-8fbc-499c-9722-09b29b707022.png)

With labeling, it can be easy to navigate & explore the form data:
![image](https://user-images.githubusercontent.com/38855190/219967919-3d29a1d5-bab7-41e2-bd96-942157a5fa44.png)

Code can be as simple as:
https://github.com/MiroslavPetrik/form-atoms-field/commit/2d4342062b251850e157d19daec58817c6884b37

**Comment by jaredLunde** [comment]
Looks good. One nit - would only want to add these labels in the development environment
