### ISSUE TITLE
Permit array as root form fields

### ISSUE THREAD

**Issue by MiroslavPetrik** [jaredLunde/form-atoms#42]
Currently the fields passed to a `formAtom()` must be an object.
```ts
type FormFields = {
    [key: string | number]: FieldAtom<any> | FormFields | FormFields[] | FieldAtom<any>[];
};
```
It could be generalized, to accept also array:

```ts
type FormArrayFields = FormFields[] | FieldAtom<any>[];
type FormFields = {
    [key: string | number]: FieldAtom<any> | FormFields | FormArrayFields;
} | FormArrayFields;
```

This could enable the submit value to be passed directly to some endpoints. For example, when configuring contact persons, I can submit the form data directly, as my endpoint expects array payload.

Currently, best we can do is to have the contact persons under some key in the form, which requires us to unwrap the data on submit:
```ts
const contactsForm = formAtom({persons: [...]}) // must use arbitrary key just to fulfil the interface

const { submit } = useForm(contactsForm)
// unnecessary unwrapping required
<form onSubmit={submit(({ persons }) => saveContactPersons(persons))}>
```

This could be:
```ts
const contactsForm = formAtom([...]) // array form fields

const { submit } = useForm(contactsForm)

<form onSubmit={submit(saveContactPersons)}>
```

**Comment by jaredLunde** [comment]
Have to think about this one. Seems like a minor inconvenience for users and a limited use case.
