### ISSUE TITLE
What's the reason for limiting setting the initial value only once?

### ISSUE THREAD

**Issue by schiller-manuel** [jaredLunde/form-atoms#52]
The docs say about [`useFieldInitialValue`](https://github.com/jaredLunde/form-atoms#usefieldinitialvalue):

> Initial values can only be set once per scope. Therefore, if the initial value used is changed during rerenders, it won't update the atom value.

But where does this limitation come from?
Why can't the initial value be updated as follows?

```typescript
function useFieldInitialValue<Value>(
  fieldAtom: FieldAtom<Value>,
  initialValue?: Value,
  options?: UseAtomOptions,
): UseFieldInitialValue {
  const field = useAtomValue(fieldAtom, options);
  const store = useStore(options);

  useEffect(() => {
    if (initialValue === undefined) {
      return;
    }
    if (store.get(field._initialValue) === initialValue) {
      return;
    }
    if (!store.get(field.dirty)) {
      store.set(field.value, initialValue);
    }
    store.set(field._initialValue, initialValue);
  }, [store, field._initialValue, field.value, field.dirty, initialValue]);
}

**Comment by jaredLunde** [comment]
what's the use case?

**Comment by jaredLunde** [comment]
i think the biggest annoyance would be forcing people to use `useMemo` on their initial values (objects, arrays, etc) but i don't recall what other reason i had if there was one

**Comment by schiller-manuel** [comment]
I have an edit form where the data is loaded through react-query which uses an stale-while-revalidate caching strategy. This means the form is populated with possibly outdated data, then the data is reloaded in the background while the form is already mounted and then some fields' initial value may be updated.

**Comment by schiller-manuel** [comment]
BTW: could the "first" initial values be set using (`useHydrateAtoms`)[https://github.com/pmndrs/jotai/blob/main/src/react/utils/useHydrateAtoms.ts] and only subsequent changes to the initial value would be done through `useEffect`?

**Comment by jaredLunde** [comment]
Hmm that's a reasonable case. I think I might have used `useHydrateAtoms` in an older version but the API didn't work with things like the the `store.get(field.dirty)` check. You cool to submit a PR?

**Comment by schiller-manuel** [comment]
do you think that equality check I added in the above code is necessary?

**Comment by jaredLunde** [comment]
Should the expected behavior for going from defined to undefined be that the value clears? It seems so, right? In that case the check would have to go

**Comment by schiller-manuel** [comment]
I played around with removing `initialValue === undefined`, turns out would cause issues if one uses `useFieldInitialValue` in combination with e.g. `useInputField` as the latter would issue a call to `useFieldInitialValue` with `initialValue=undefined`.

So we would need another value as a "reset" signal, how about `RESET`?
